### PR TITLE
Replace `ava` test runner with `vitest`

### PR DESCRIPTION
**Pull request by janosh**
`vitest` is a brand new test runner specifially built for our build tool `vite` with an extremely fast watch mode. I.e. you can leave `vitest` running while you develop and it automatically reruns tests when any of the code it covers changes.

### CODE REVIEW

**Comment by janosh** [comment]
@l8l I think you'll like this change as it reduces the number of NPM packages we depend on quite a bit. Running our tests through the same tool that builds our site also means no duplicate configuration (any config we write automatically applies to both the site and our tests) and  all tests can now be written in TypeScript which in fact revealed a few type errors I had made in our earlier tests.

**Comment by l8l** [comment]
Sounds really good = )

**Comment by janosh** [comment]
More good news: `svelte-multiselect` got a big update today with lots of fixes that will be part of this PR.

https://github.com/janosh/svelte-multiselect/releases/tag/v4.0.1

**Comment by janosh** [comment]
Btw, if there's ever a problem with the signup forms you can call `yarn test` locally to have them auto-filled and see what might be going wrong if a field stays empty or an error appears after form submission. Looks like this:

https://user-images.githubusercontent.com/30958850/156899999-44ec1dd9-5b89-4db0-9b91-2d20f2c861ff.mp4

**Comment by l8l** [comment]
Thanks a lot. For better understanding: When submitting this test form, is the data sent to airtable or not and where to inspect errors?

**Comment by janosh** [comment]
Yes, sent to a test base in Airtable. Inspect errors either directly in the browser UI, the browser's console or in your terminal.

**Comment by l8l** [comment]
Okay, perfect.

**Pull request merged**
