### PR TITLE
Prerender all sites

### LINKED ISSUE #19: Crawling of all sites during build
Currently not all pages are build, since there are only links from the nav to these pages.

A crawler which finds all pages need to be readded.

### PR DESCRIPTION
**Pull request by janosh**
Closes #19.

### CODE REVIEW

**Comment by janosh** [comment]
Seems to solve the problem. E.g. https://deploy-preview-20--sbsev.netlify.app/kontakt is now directly reachable. But creates new problem. All subnavs now briefly flash on page load.

**Comment by janosh** [comment]
Last commit does not prevent flashing sub navs.

**Comment by janosh** [comment]
I guess that leaves making hacky solutions like adding `z-index: -1`/`opacity: 0` to hide sub navs on page load.

**Comment by janosh** [comment]
I guess that leaves hacky solutions like adding `z-index: -1`/`opacity: 0` to hide sub navs on page load.

**Comment by janosh** [comment]
Or we add all those links into the footer and render them at all times. Lots of sites do that. E.g. [Apple](https://apple.com):

Screen Shot 2022-03-05 at 11 27 34

**Comment by janosh** [comment]
Something like this:

Screen Shot 2022-03-05 at 11 44 40

**Comment by l8l** [comment]
I'd prefer not adding an additional menu at the bottom but if there is no other solution (apart from manually adding those links that the crawler can't find), then it's okay for me. However, when clicking on the link above, I get a scroll bar between "Standorte" and "Mitmachen" that shouldn't be there:
Bildschirmfoto_2022-03-05_13-01-58

**Comment by janosh** [comment]
@l8l We don't have to show the links. We can add them into our HTML but make them invisible.

**Comment by janosh** [comment]
@l8l Can you check the deploy preview for b13c09b and see if there are any visual artifacts from the hidden links I added to the nav?

**Comment by janosh** [comment]
If so, try adding additional styles like `opacity: 0` or `z-index: -1` here and see if the artifacts disappear: https://github.com/sbsev/svelte-site/blob/b13c09b2a0116999ad92cf6ef398ec7a0348198e/src/components/Nav.svelte#L51-L56

**Comment by l8l** [comment]
Okay, good idea to hide them away. I pulled the new branch and checked it locally, there are no artifacts, looks fine = ). Thanks.

**Comment by janosh** [comment]
@l8l Thanks, then let's ship this!

**Pull request merged**
